MacOsDir=MacOs
WebDir=Web
WindowsDir=Windows

all:
	g++ -o main main.cpp MacOs/MacOsDialog.cpp Web/WebDialog.cpp Windows/WindowsDialog.cpp MacOs/MacOsButton.cpp Web/WebButton.cpp Windows/WindowsButton.cpp MacOs/MacOsTextBox.cpp Web/WebTextBox.cpp Windows/WindowsTextBox.cpp -I. -IMacOs -IWeb -IWindows
